services:
  # Smokebox (Test) Environment
  - type: web
    name: dialogue-foundry-backend-smokebox
    env: node
    rootDir: apps/backend
    buildCommand: pnpm install --no-frozen-lockfile; pnpm build
    startCommand: pnpm start
    region: oregon
    plan: standard
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEPLOYMENT_ENV
        value: smokebox
      - key: PORT
        value: 8080
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_SENDGRID_TEMPLATE_ID
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
    autoDeploy: true
  
  # Production Environment
  - type: web
    name: dialogue-foundry-backend-prod
    env: node
    rootDir: apps/backend
    buildCommand: pnpm install --no-frozen-lockfile; pnpm build
    startCommand: pnpm start
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEPLOYMENT_ENV
        value: production
      - key: PORT
        value: 8080
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: DEFAULT_SENDGRID_TEMPLATE_ID
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY
        sync: false
    # Disable auto-deploy for production
    autoDeploy: false 