app = "convostack-getting-started"
primary_region = "iad"

[env]
  ALLOW_ANONYMOUS_USERS = "true"
  CORS_ALLOWED_ORIGINS = "http://localhost:3000,http://localhost:5173,https://studio.apollographql.com,https://convostack-getting-started.fly.dev,https://convostack.ai,https://docs.convostack.ai,https://playground.convostack.ai"
  HOST = "0.0.0.0"
  PORT = "3000"
  REQUIRE_USER_VERIFICATION_HASH = "false"
  STORAGE_ENGINE = "postgres"
  NODE_ENV = "production"
  # We suggest disabling this for your own application
  # GQL inspection is enabled on the playground for better API discoverability, but is typically not desirable
  ENABLE_GQL_INTROSPECTION = "true"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [services.http_checks]
    path = "/api/agents"
    interval = "15s"
    timeout = "5s"
