name: Deploy Packages to S3

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/deploy-to-s3.yml'

jobs:
  build_and_deploy:
    name: Build and Deploy
    # Only run when PR is merged to main, not on every PR close
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for Turborepo to detect changes
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build all packages
        run: |
         pnpm build
      
      - name: Debug environment variables
        run: |
          echo "Checking GitHub secrets and environment variables"
          if [ -n "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "Secret AWS_ACCESS_KEY_ID is configured"; else echo "Secret AWS_ACCESS_KEY_ID is NOT configured"; fi
          if [ -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then echo "Secret AWS_SECRET_ACCESS_KEY is configured"; else echo "Secret AWS_SECRET_ACCESS_KEY is NOT configured"; fi
          
      
      - name: Deploy packages
        id: deploy
        run: |
          echo "Running publish-package script with credentials"
          
          # Create a wrapper script that sets the environment variables correctly
          cat > deploy-wrapper.sh << 'EOF'
          #!/bin/bash
          # Export AWS credentials to environment variables for the Node.js process
          export AWS_ACCESS_KEY_ID="$1"
          export AWS_SECRET_ACCESS_KEY="$2"
          
          # Run the publish-package command
          pnpm publish-package
          EOF
          
          chmod +x deploy-wrapper.sh
          
          # Execute the wrapper script, passing the credentials as arguments
          ./deploy-wrapper.sh "${{ secrets.AWS_ACCESS_KEY_ID }}" "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          
          # Clean up
          rm deploy-wrapper.sh
      
      - name: Create deployment summary
        run: |
          echo "## 📦 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Package | Version | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| ------- | ------- | ------ |" >> $GITHUB_STEP_SUMMARY
          
          # We'll list the packages that have the publish-package script
          for pkg in $(find apps packages -name "package.json" -not -path "*/node_modules/*" -not -path "*/dist/*" | sort); do
            if grep -q '"publish-package":' "$pkg"; then
              dir=$(dirname "$pkg")
              name=$(node -p "require('./$pkg').name")
              version=$(node -p "require('./$pkg').version")
              status="✅"
            fi
          done
