name: Publish Packages

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/publish-packages.yml'
      
jobs:
  build_and_deploy:
    name: Build and Deploy
    
    permissions:
      packages: write
      contents: read
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for Turborepo to detect changes
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dialogue-foundry'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build all packages
        run: |
          echo "Building all packages..."
          pnpm build
      
      - name: Deploy packages
        id: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Running publish-package scripts..."
          pnpm publish-package
      
      - name: Create deployment summary
        run: |
          echo "## 📦 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Package | Version | Status |" >> $GITHUB_STEP_SUMMARY
          echo "| ------- | ------- | ------ |" >> $GITHUB_STEP_SUMMARY
          
          # We'll list the packages that have the publish-package script
          for pkg in $(find apps packages -name "package.json" -not -path "*/node_modules/*" -not -path "*/dist/*" | sort); do
            if grep -q '"publish-package":' "$pkg"; then
              dir=$(dirname "$pkg")
              name=$(node -p "require('./$pkg').name")
              version=$(node -p "require('./$pkg').version")
              echo "| $name | $version | ✅ |" >> $GITHUB_STEP_SUMMARY
            fi
          done
